// centaurea-ui-react/src/components/ComputedTimeModal.jsx
import React from 'react';
import { createPortal } from 'react-dom';

function ComputedTimeModal({
  isOpen,
  value,
  maxValue,
  isFuture,
  isSaving,
  onChange,
  onCancel,
  onSave
}) {
  if (!isOpen) return null;
  if (typeof document === 'undefined') return null;

  const modalContent = (
    <div className="modal-overlay" onClick={onCancel}>
      <div className="modal" onClick={(event) => event.stopPropagation()}>
        <h3 className="modal__title">Update Computed Time</h3>
        <div className="modal__content">
          <div className="form__group">
            <label className="form__label">Select a date and time (must be in the past)</label>
            <input
              type="datetime-local"
              className="form__input"
              value={value}
              max={maxValue}
              onChange={(event) => onChange(event.target.value)}
              autoFocus
            />
            {isFuture && <div className="modal__hint">Time must be in the past.</div>}
          </div>
        </div>
        <div className="modal__actions">
          <button
            type="button"
            className="button button--secondary"
            onClick={onCancel}
            disabled={isSaving}
          >
            Cancel
          </button>
          <button
            type="button"
            className="button button--primary"
            onClick={onSave}
            disabled={!value || isFuture || isSaving}
          >
            Save Changes
          </button>
        </div>
      </div>
    </div>
  );

  return createPortal(modalContent, document.body);
}

export default ComputedTimeModal;

// centaurea-ui-vue3/src/components/ComputedTimeModal.vue
<template>
  <Teleport to="body">
    <div class="modal-overlay" @click="emitCancel">
      <div class="modal" @click.stop>
        <h3 class="modal__title">Update Computed Time</h3>
        <div class="modal__content">
          <div class="form__group">
            <label class="form__label">Select a date and time (must be in the past)</label>
            <input
              type="datetime-local"
              class="form__input"
              :value="modelValue"
              :max="maxValue"
              @input="onInput"
              ref="inputRef"
            />
            <div v-if="isFuture" class="modal__hint">Time must be in the past.</div>
          </div>
        </div>
        <div class="modal__actions">
          <button
            type="button"
            class="button button--secondary"
            :disabled="isSaving"
            @click="emitCancel"
          >
            Cancel
          </button>
          <button
            type="button"
            class="button button--primary"
            :disabled="!modelValue || isFuture || isSaving"
            @click="emitSave"
          >
            Save Changes
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup>
import { ref, onMounted } from 'vue';

const props = defineProps({
  modelValue: {
    type: String,
    default: ''
  },
  maxValue: {
    type: String,
    default: ''
  },
  isFuture: {
    type: Boolean,
    default: false
  },
  isSaving: {
    type: Boolean,
    default: false
  }
});

const emit = defineEmits(['update:modelValue', 'cancel', 'save']);

const inputRef = ref(null);

onMounted(() => {
  if (inputRef.value) {
    inputRef.value.focus();
  }
});

const onInput = (event) => {
  emit('update:modelValue', event.target.value);
};

const emitCancel = () => emit('cancel');
const emitSave = () => emit('save');
</script>
