// centaurea-ui-react/src/components/ErrorBoundary.jsx
import { Component } from 'react';
import Button from './Button';
import Section from './Section';
import SectionHeader from './SectionHeader';
import StatusMessage from './StatusMessage';

class ErrorBoundary extends Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError() {
    return { hasError: true };
  }

  componentDidCatch(error) {
    console.error('Unhandled render error:', error);
  }

  handleTryAgain = () => {
    this.setState({ hasError: false });
  };

  render() {
    if (this.state.hasError) {
      return (
        <Section>
          <SectionHeader title="Something went wrong" />
          <StatusMessage variant="error">
            An unexpected UI error occurred. Please try again.
          </StatusMessage>
          <Button type="button" onClick={this.handleTryAgain}>
            Try Again
          </Button>
        </Section>
      );
    }

    return this.props.children;
  }
}

export default ErrorBoundary;

// centaurea-ui-vue3/src/components/ErrorBoundary.vue
<script setup>
import { onErrorCaptured, ref } from 'vue';
import CustomButton from '@/components/CustomButton.vue';
import PageSection from '@/components/PageSection.vue';
import PageSectionHeader from '@/components/PageSectionHeader.vue';
import StatusMessage from '@/components/StatusMessage.vue';

const hasError = ref(false);

onErrorCaptured((error) => {
  console.error('Unhandled render error:', error);
  hasError.value = true;
  return false;
});

const handleTryAgain = () => {
  hasError.value = false;
};
</script>

<template>
  <PageSection v-if="hasError">
    <PageSectionHeader title="Something went wrong" />
    <StatusMessage variant="error">
      An unexpected UI error occurred. Please try again.
    </StatusMessage>
    <CustomButton type="button" @click="handleTryAgain">Try Again</CustomButton>
  </PageSection>
  <slot v-else />
</template>
