// centaurea-ui-react/src/components/NotificationStack.jsx
import StatusMessage from './StatusMessage';

function NotificationStack({ notifications = [], onDismiss }) {
  if (!notifications.length) return null;

  return (
    <div className="notification-stack" aria-live="assertive" aria-atomic="true">
      {notifications.map((notification) => (
        <StatusMessage
          key={notification.id}
          variant={notification.variant}
          className="notification-stack__item"
        >
          <span className="notification-stack__message">{notification.message}</span>
          <button
            type="button"
            className="notification-stack__close"
            onClick={() => onDismiss?.(notification.id)}
            aria-label="Close notification"
          >
            ×
          </button>
        </StatusMessage>
      ))}
    </div>
  );
}

export default NotificationStack;

// centaurea-ui-vue3/src/components/NotificationStack.vue
<script setup>
import StatusMessage from '@/components/StatusMessage.vue';

const props = defineProps({
  notifications: {
    type: Array,
    default: () => [],
  },
});

const emit = defineEmits(['dismiss']);

const handleDismiss = (id) => {
  emit('dismiss', id);
};
</script>

<template>
  <div v-if="props.notifications.length" class="notification-stack" aria-live="assertive" aria-atomic="true">
    <StatusMessage
      v-for="notification in props.notifications"
      :key="notification.id"
      :variant="notification.variant"
      class-name="notification-stack__item"
    >
      <span class="notification-stack__message">{{ notification.message }}</span>
      <button
        type="button"
        class="notification-stack__close"
        aria-label="Close notification"
        @click="handleDismiss(notification.id)"
      >
        ×
      </button>
    </StatusMessage>
  </div>
</template>
