// centaurea-ui-react/src/App.js
import React, { useEffect, useState } from 'react';
import { BrowserRouter, Routes, Route, Navigate, NavLink } from 'react-router-dom';
import 'centaurea-ui-shared/styles';
import { appStore } from './store/appStore';
import AuthPage from './pages/AuthPage';
import CalculatorPage from './pages/CalculatorPage';
import HistoryPage from './pages/HistoryPage';
import SamplesPage from './pages/SamplesPage';
import AdminPage from './pages/AdminPage';
import { authService } from './services/authService';

function App() {
  const [currentUser, setCurrentUser] = useState(appStore.getUser());

  useEffect(() => {
    const handleStateChange = (state) => {
      setCurrentUser(state.user);
    };
    const unsubscribe = appStore.subscribe(handleStateChange);
    return unsubscribe;
  }, []);

  const handleSignOut = () => {
    authService.signOut();
    appStore.setUser(null);
  };

  return (
    <BrowserRouter>
      <div className="app-container">
        <div className="container">
          <div className="header">
            <h1 className="header__title">Expression Calculator (React)</h1>
            {currentUser && (
              <div className="user-badge">
                <div className="user-badge__info">
                  <div className="user-badge__name">{currentUser.name}</div>
                  <div className="user-badge__email">{currentUser.email}</div>
                </div>
                <button className="user-badge__button" onClick={handleSignOut}>
                  Sign out
                </button>
              </div>
            )}
          </div>

          {currentUser && (
            <nav className="tabs">
              <NavLink
                to="/calculator"
                className={({ isActive }) => `tabs__item${isActive ? ' tabs__item--active' : ''}`}
              >
                Calculator
              </NavLink>
              <NavLink
                to="/history"
                className={({ isActive }) => `tabs__item${isActive ? ' tabs__item--active' : ''}`}
              >
                History
              </NavLink>
              <NavLink
                to="/samples"
                className={({ isActive }) => `tabs__item${isActive ? ' tabs__item--active' : ''}`}
              >
                Samples
              </NavLink>
            </nav>
          )}

          <Routes>
            <Route
              path="/auth"
              element={currentUser ? <Navigate to="/calculator" replace /> : <AuthPage />}
            />
            <Route
              path="/calculator"
              element={currentUser ? <CalculatorPage /> : <Navigate to="/auth" replace />}
            />
            <Route
              path="/history"
              element={currentUser ? <HistoryPage /> : <Navigate to="/auth" replace />}
            />
            <Route
              path="/samples"
              element={<SamplesPage />}
            />
            <Route
              path="/admin"
              element={<AdminPage />}
            />
            <Route
              path="*"
              element={<Navigate to={currentUser ? '/calculator' : '/auth'} replace />}
            />
          </Routes>
        </div>
      </div>
    </BrowserRouter>
  );
}

export default App;

// centaurea-ui-vue3/src/App.vue
<script>
import { appStore } from './store/appStore';
import { authService } from './services/authService';
import 'centaurea-ui-shared/styles';

export default {
  data() {
    return {
      currentUser: appStore.getUser(),
      unsubscribe: null
    };
  },
  mounted() {
    this.unsubscribe = appStore.subscribe((state) => {
      this.currentUser = state.user;
    });
  },
  unmounted() {
    this.unsubscribe?.();
  },
  methods: {
    handleSignOut() {
      authService.signOut();
      appStore.setUser(null);
      this.$router.push('/auth');
    }
  }
};
</script>

<template>
  <div class="app-container">
    <div class="container">
      <div class="header">
        <h1 class="header__title">Expression Calculator (Vue3)</h1>
        <div v-if="currentUser" class="user-badge">
          <div class="user-badge__info">
            <div class="user-badge__name">{{ currentUser.name }}</div>
            <div class="user-badge__email">{{ currentUser.email }}</div>
          </div>
          <button class="user-badge__button" @click="handleSignOut">Sign out</button>
        </div>
      </div>

      <nav v-if="currentUser" class="tabs">
        <router-link to="/calculator" class="tabs__item" active-class="tabs__item--active">
          Calculator
        </router-link>
        <router-link to="/history" class="tabs__item" active-class="tabs__item--active">
          History
        </router-link>
        <router-link to="/samples" class="tabs__item" active-class="tabs__item--active">
          Samples
        </router-link>
      </nav>

      <router-view />
    </div>
  </div>
</template>
